accounts/urls.py
from django.urls import path , include
from . import views

urlpatterns =[
    path('signup/', views.account_view),
]

articles/urls.py
from django.urls import path
from . import views
app_name="articles"
urlpatterns = [
    path('', views.articles, name="list"),
    path('<slug>', views.articles_detail, name="detail"),
]

webmidia/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length = 100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    image= models.ImageField(default='default.jpg', blank=True)
    def __str__(self):
        return self.title

    def character(self):
        return self.body[:50] + '...'

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
# Create your views here.
def account_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form':form})

articles/views.py
from django.shortcuts import render, HttpResponse
from . import models
# Create your views here.
def articles(request):
    articles = models.Article.objects.all().order_by('date')
    args = {'articles':articles}
    return render(request, 'articles/articles.html', args)
def articles_detail(request, slug):
    article = models.Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article':article} )

webmidia/views.py
from django.shortcuts import render
def home(request):
    return render(request, 'home.html')

accounts/templates/accounts/signup.html
{%extends 'base.html'%}
{% block content %}
<h1>signup</h1>
  <form class="site-form" action="/accounts/signup/" method="post">
    {{form}}
    {% csrf_token %}
    <input type="submit" name="" value="submit!">
  </form>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base.html'%}
{% block content %}
<img src="{{article.image.url}}" alt="">
<h1>{{article.title}}</h1>
<p>{{article.body}}</p>

{% endblock%}

articles/templates/articles/articles.html
{% extends 'base.html' %}

{% block title %}
articles
{% endblock %}
{% block content %}
  <div class="continer">


      {% for items in articles %}
    <h2>
      <a href="{% url 'articles:detail' slug=items.slug %}">{{items.title}}</a>
    </h2>
    <p>{{items.character}}</p>
    <p>{{items.date}}</p>
    {% endfor %}

  </div>
{%endblock%}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>
      {% block title%}
      {% endblock %}
    </title>
  </head>
  <body>
<h1>{%block logo%}<a href="{% url "articles:list" %}">LOGO</a>{% endblock %}
</h1>
  {% block content%}

  {%endblock%}

  </body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>home</h1>
  </body>
</html>